#ifndef ACTIVITYLIBRARY_GLOBAL_H
#define ACTIVITYLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ACTIVITYLIBRARY_LIBRARY)
#  define ACTIVITYLIBRARY_EXPORT Q_DECL_EXPORT
#else
#  define ACTIVITYLIBRARY_EXPORT Q_DECL_IMPORT
#endif

#endif // ACTIVITYLIBRARY_GLOBAL_H
